---
documentaclass: article
fontsize: 12pt

lang: es

# indent: true
indent: false

geometry:
- margin = 2cm
- includefoot
- a4paper

header-includes:
- \usepackage{graphicx}
- \usepackage{booktabs}
- \usepackage{icomma}

titulo: "Trabajo práctico 1"
# tema: Tema trabajo práctico
carrera: FCEIA
materia: Procesamiento del Lenguaje Natural
# comision: "Comisión #"
fecha: Noviembre, 2023.

integrante:
- Garay Gorta, Isaías.
- Petetta, Nicola.
- Segui, Eduardo.

docente:
- Cavallo, Andrea.
- Geary, Alan.
- Manson, Juan Pablo.
---
